target-version = "py311"
line-length = 100

src = ["apps/*/src", "libs/*/src"]


[lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
]
fixable = ["ALL"]

[lint.isort]
known-first-party = ["monetary", "budgets"]

[format]
quote-style = "double"
indent-style = "space"
