target-version = "py311"
line-length = 100

src = ["apps", "libs"]

[lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
]
fixable = ["ALL"]

[lint.isort]
known-first-party = ["apps", "libs"]

[format]
quote-style = "double"
indent-style = "space"
